### ISSUE TITLE
Add a `clean_anzsic` function like the `strayr` function

### ISSUE THREAD

**Issue by daviddiviny** [MattCowgill/readabs#124]
This would help with the issue that the part of the ABS that publishes the weekly payroll and wages data likes to prepend numbers and letters and take an inconsistent approach to capitalisation and use of ampersands. 

_Weekly Payroll Jobs and Wages_

`01. A-Agriculture,   forestry & fishing

_6291.0.55.001   Labour Force, Australia, Detailed_

Agriculture, Forestry and Fishing

**Comment by MattCowgill** [comment]
Ooh yes, I like this idea. Could also do ANZSCO as well as various ASGS-related functions (eg. what SA4 is this SA2 in?) 

I wonder whether this function/these functions are best off as part of readabs, or in another package.

**Comment by daviddiviny** [comment]
I think they could happily live in `readabs` because they are about conforming data to the ABS standard classification, but it could also be the start of a new package for the `runapp` community. 

I don't know if that specific ASGS-related function is needed? The data is already in the tables in `absmapsdata` (see below). However, you could do something to clean names of LGAs etc? 
```
library(absmapsdata)
library(sf)
library(tidyverse)

sa32016 %>%  
  filter(sa3_name_2016 == "Yarra") %>% 
  pull(sa4_name_2016)
```

**Comment by hamgamb** [comment]
I'm not sure what approach you were thinking of taking with this but for the payroll data (table 4):

```
# A tibble: 6 x 6
  state_or_territory industry_division sex        age_group   date   value
  <chr>              <chr>             <chr>      <chr>       <chr>  <dbl>
1 0. Australia       0. All industries 0. Persons 0. All ages x43834  92.9
2 0. Australia       0. All industries 0. Persons 0. All ages x43841  95.3
3 0. Australia       0. All industries 0. Persons 0. All ages x43848  96.8
4 0. Australia       0. All industries 0. Persons 0. All ages x43855  97.6
5 0. Australia       0. All industries 0. Persons 0. All ages x43862  98.1
6 0. Australia       0. All industries 0. Persons 0. All ages x43869  98.8
```

I've got: `    mutate(across(1:5, ~ gsub("^[0-9]\\. ", "", .)), industry_division = gsub("(0[0-9]|1[0-9])\\. ([A-S]-)", "", industry_division)`  to remove the zeros (from everything) and letters from the industries.

```
# A tibble: 6 x 6
  state_or_territory industry_division sex     age_group date   value
  <chr>              <chr>             <chr>   <chr>     <chr>  <dbl>
1 Australia          All industries    Persons All ages  x43834  92.9
2 Australia          All industries    Persons All ages  x43841  95.3
3 Australia          All industries    Persons All ages  x43848  96.8
4 Australia          All industries    Persons All ages  x43855  97.6
5 Australia          All industries    Persons All ages  x43862  98.1
6 Australia          All industries    Persons All ages  x43869  98.8
```

Maybe it helps, maybe it doesn't!

**Comment by daviddiviny** [comment]
Yep - my code for cleaning it looks something like this, but I wonder we can do something more generalisable for other weird versions? 

``` r
    mutate(across(state_or_territory:age_group, ~ str_remove(., pattern = "\\d+\\. ")),
           industry_division = str_remove(industry_division,  "[:upper:]?-+"),
           industry_division = tools::toTitleCase(industry_division),
           industry_division = str_replace_all(industry_division, "&", "and"),
           state_or_territory = if_else(state_or_territory == "Australia", "Australia",
                                        strayr(state_or_territory, to = "state_name", fuzzy_match = FALSE)))
```

**Comment by MattCowgill** [comment]
Yep. I agree there would be value in generalising this. Virtually every release that uses ANZSIC (and ANZSCO) varies slightly in the punctuation, etc.

**Comment by daviddiviny** [comment]
Closing as moved to `abscorr`.
