### ISSUE TITLE
Unsuccessful download from read_abs( id ="6302.0")

### ISSUE THREAD

**Issue by yytsong** [MattCowgill/readabs#128]
Hi,

Really appreciate the package you shared. 

When feeding an id = "6302.0" (average week learning) into the function, it starts with assembling the URL and broke after the first downloading link, but other ids seem to be fine. Not sure if this is an issue on the ABS side or the links were not detected.
The same setting was used before and it was functional. 

--- error message below ---- 
Finding filenames for tables corresponding to ABS catalogue 6302.0
Attempting to download files from catalogue 6302.0, Average Weekly Earnings, Australia
Downloading https://www.abs.gov.au/statistics/labour/earnings-and-work-hours/average-weekly-earnings-australia/latest-release/6302001.xls
 [100%] Downloaded 634 bytes...
 Downloaded 21042 bytes...Error in curl::curl_download(url = url, destfile = filename, mode = "wb",  : 
  HTTP error 404.

**Comment by MattCowgill** [comment]
Thanks @yytsong, I'll try to figure out what's happening here. 

In the meantime, you might find the `readabs::read_awe()` function useful (update to the latest {readabs} if you don't have that function).

**Comment by MattCowgill** [comment]
Hi @yytsong,
I've figured out what the issue is. The ABS has (temporarily?) removed spreadsheets containing 'trend' estimates. Unfortunately, they have not removed these tables from the Time Series Directory, the API that readabs queries to find tables that match your query. I have contacted the ABS and asked them to remedy this.

In the meantime, you can get any of the seasonally adjusted or original series from this release; see here for the list: https://www.abs.gov.au/statistics/labour/earnings-and-work-hours/average-weekly-earnings-australia/latest-release#data-download. 

For example, this works fine:

``` r
readabs::read_abs("6302.0", "2")
#> Finding filenames for tables corresponding to ABS catalogue 6302.0
#> Attempting to download files from catalogue 6302.0, Average Weekly Earnings, Australia
#> Downloading https://www.abs.gov.au/statistics/labour/earnings-and-work-hours/average-weekly-earnings-australia/latest-release/6302002.xls
#> Extracting data from downloaded spreadsheets
#> Tidying data from imported ABS spreadsheets
#> # A tibble: 162 x 12
#>    table_no sheet_no table_title   date       series value series_type data_type
#>    <chr>    <chr>    <chr>         <date>     <chr>  <dbl> <chr>       <chr>    
#>  1 6302002  Data1    TABLE 2. Ave… 2012-05-15 Earni… 1444. Seasonally… RATIO    
#>  2 6302002  Data1    TABLE 2. Ave… 2012-05-15 Earni… 1537. Seasonally… RATIO    
#>  3 6302002  Data1    TABLE 2. Ave… 2012-05-15 Earni… 1285. Seasonally… RATIO    
#>  4 6302002  Data1    TABLE 2. Ave… 2012-05-15 Earni… 1192. Seasonally… RATIO    
#>  5 6302002  Data1    TABLE 2. Ave… 2012-05-15 Earni… 1209. Seasonally… RATIO    
#>  6 6302002  Data1    TABLE 2. Ave… 2012-05-15 Earni…  822. Seasonally… RATIO    
#>  7 6302002  Data1    TABLE 2. Ave… 2012-05-15 Earni… 1349. Seasonally… RATIO    
#>  8 6302002  Data1    TABLE 2. Ave… 2012-05-15 Earni… 1416. Seasonally… RATIO    
#>  9 6302002  Data1    TABLE 2. Ave… 2012-05-15 Earni… 1053. Seasonally… RATIO    
#> 10 6302002  Data1    TABLE 2. Ave… 2012-11-15 Earni… 1492. Seasonally… RATIO    
#> # … with 152 more rows, and 4 more variables: collection_month <chr>,
#> #   frequency <chr>, series_id <chr>, unit <chr>
```

<sup>Created on 2021-03-03 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by MattCowgill** [comment]
The ABS has resolved this issue by removing unavailable tables from the Time Series Directory. I've confirmed that `readabs::read_abs("6302.0")`  now returns the expected output without error. I'd encourage you to have a look at the `read_awe()` function to see if it meets your needs as well @yytsong.
