### ISSUE TITLE
Downloading then reading XML slows down read_abs

### ISSUE THREAD

**Issue by MattCowgill** [MattCowgill/readabs#142]
Recent changes removed the dependency on the `curl` package, to enable users on networks where curl is blocked to still use `{readabs}`. See PR (https://github.com/MattCowgill/readabs/pull/141) and discussion (https://github.com/MattCowgill/readabs/issues/133).

This has slowed down `readabs::read_abs()`. One reason is that XML files are now downloaded to disk before being read, which takes about twice as long. See benchmarks below. 

**Any suggestions for speeding up this code in a way that does not use curl/httr would be most appreciated!**

``` r
url <- "https://ausstats.abs.gov.au/servlet/TSSearchServlet?catno=6345.0&ttitle=1"

# Current method, slow
f1 <- function(url) {
  temp_xml <- tempfile(fileext = ".xml")
  download.file(url = url, destfile = temp_xml)
  xml2::read_xml(temp_xml, encoding = "ISO-8859-1")
}

# Previous method, fast, doesn't work on certain networks
f2 <- function(url) {
  xml2::read_xml(url,
                 encoding = "ISO-8859-1")
}

bench::mark(f1(url), f2(url))
#> # A tibble: 2 x 6
#>   expression      min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 f1(url)       380ms    428ms      2.34     492KB        0
#> 2 f2(url)       156ms    159ms      6.16     352KB        0
```

<sup>Created on 2021-04-17 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by daviddiviny** [comment]
I am not familiar with this issue but is it possible to only use the slow method if it detects a problem with the network?

**Comment by nerskin** [comment]
I've tried this a number of times and consistently get much smaller timing differences, e.g.

``` r
url <- "https://ausstats.abs.gov.au/servlet/TSSearchServlet?catno=6345.0&ttitle=1"

# Current method, slow
f1 <- function(url) {
  temp_xml <- tempfile(fileext = ".xml")
  download.file(url = url, destfile = temp_xml)
  xml2::read_xml(temp_xml, encoding = "ISO-8859-1")
}

# Previous method, fast, doesn't work on certain networks
f2 <- function(url) {
  xml2::read_xml(url,
                 encoding = "ISO-8859-1")
}
bench::mark(f1(url), f2(url),min_iterations=10)
#> # A tibble: 2 x 6
#>   expression      min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 f1(url)       343ms    442ms      2.33     491KB        0
#> 2 f2(url)       316ms    347ms      2.86     353KB        0
```

<sup>Created on 2021-04-17 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by nerskin** [comment]
I've taken a slightly closer look at the timings and I really don't know what to make of it 

``` r
url <- "https://ausstats.abs.gov.au/servlet/TSSearchServlet?catno=6345.0&ttitle=1"

# Current method, slow
f1 <- function(url) {
  temp_xml <- tempfile(fileext = ".xml")
  download.file(url = url, destfile = temp_xml)
  xml2::read_xml(temp_xml, encoding = "ISO-8859-1")
}

# Previous method, fast, doesn't work on certain networks
f2 <- function(url) {
  xml2::read_xml(url,
                 encoding = "ISO-8859-1")
}

library(tidyverse)

f2_times <- bench::mark(f2(url),iterations=100)$time
f1_times <- bench::mark(f1(url),iterations=100)$time

timings <- tibble(iteration=rep(1:100,2),time=c(f1_times[[1]],f2_times[[1]]),f=c(rep('f1',100),rep('f2',100))) 

ggplot(timings,aes(time,f)) + geom_boxplot()
```

![](https://i.imgur.com/p7iUdeo.png)

<sup>Created on 2021-04-17 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by HughParsonage** [comment]
This is purely a caching effect. The first download is always slowest, either through session-caching or server-side caching.

**Comment by rensa** [comment]
Gonna cross-post from Slack here! `f3` is my proposed implementation:

```r
library(openssl)

url <-
  "https://ausstats.abs.gov.au/servlet/TSSearchServlet?catno=6345.0&title=1"

f1 <- function(url) {
  temp_xml <- tempfile(fileext = ".xml")
  download.file(url = url, destfil = temp_xml, mode = "wb")
  xml2::read_xml(temp_xml, encoding = "ISO-8859-1")
}

f2 <- function(url) {
  xml2::read_xml(url, encoding = "ISO-8859-1")
}

f3 <- function(url) {
  xml2::read_xml(file(url, encoding = "ISO-8859-1"), encoding = "ISO-8859-1")
}
```

On Windows:

```r
> bench::mark(f1(url), f2(url), f3(url), iterations = 100)
# A tibble: 3 x 13
  expression     min  median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time
  <bch:expr> <bch:t> <bch:t>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm>
1 f1(url)     36.5ms    43ms     21.4       704B        0   100     0      4.67s
2 f2(url)     94.3ms 107.4ms      8.42     136KB        0   100     0     11.87s
3 f3(url)     23.7ms  29.6ms     27.9      129KB        0   100     0      3.58s
# ... with 4 more variables: result <list>, memory <list>, time <list>,
#   gc <list>
```

On WSL:

```r
> bench::mark(f1(url), f2(url), f3(url), iterations = 100)
# A tibble: 3 x 13
  expression     min  median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time
  <bch:expr> <bch:t> <bch:t>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm>
1 f1(url)     80.5ms  91.2ms      3.53      704B        0   100     0      28.3s
2 f2(url)    103.2ms 116.7ms      6.39     136KB        0   100     0      15.6s
3 f3(url)     80.1ms  89.4ms      7.43     129KB        0   100     0      13.5s
# … with 4 more variables: result <list>, memory <list>, time <list>, gc <list>
```

Notes:

* For me, f2 was slower than f1, not the other way around. Not what I expected!
* Not sure why the differences are less stark on WSL, although maybe routing through WSL slows things down?.
* From my understanding, `download.file` defaults to different methods depending on the platform: `wininet` for Windows and `libcurl` (not `curl`, although I don't know what the difference is) for Mac and Linux. Not sure if that impacts on your own testing or how well `f2` works in different situations!
* I haven't tested `file()` for binary URLs, like shapefiles. Maybe `raw = TRUE` is the way to go there!

Oh, and this was the result I got with all three functions on either platform:

```r
> f2(url)
{xml_document}
<Error>
```

Is that expected?
7:51
Also no idea why mem_alloc for f1 is less than 1 KB in my testing and not in yours :thinking_face:

**Comment by HughParsonage** [comment]
Also I know that I am hardly in a position to say this, but ... the "slow" function seems fast enough, Matt.

**Comment by rensa** [comment]
I should note that `download.file` uses `file` internally (so do `read.csv` and `read.table`, which is why they can take URLs directly these days—`download.file` just directs the connection to a file on disk).

So if you're happy with its network compatibility, `f3` should give completely identical network compatibility :)

**Comment by MattCowgill** [comment]
Thanks all. I like your function @rensa and will adopt that, thank you. 

@HughParsonage the issue is that when people request multiple tables or a whole catalogue number worth of ABS time series with `read_abs()` then a number of pages of XML need to be read, so small speed differences can compound. For example, `read_abs("6202.0")` reads ~52 pages of XML before it starts to download spreadsheets. So half a second here or there x 52 iterations adds up!

**Comment by HughParsonage** [comment]
Fair enough. But remember that the difference you're observing is an illusion.

**Comment by rensa** [comment]
> This is purely a caching effect. The first download is always slowest, either through session-caching or server-side caching.

Can caching explain the difference even when we're doing 100 iterations and seeing a difference in the median time?

**Comment by HughParsonage** [comment]
Not for 100 iterations. But that's not the relevant benchmark, because you're repeating the same URL. If you avoid partial argument matching and set `quiet = TRUE` the difference vanishes.

```r
f1 <- function(url) {
  temp_xml <- tempfile(fileext = ".xml")
  download.file(url = url, destfile = temp_xml, mode = "wb", quiet = TRUE)
  xml2::read_xml(temp_xml, encoding = "ISO-8859-1")
}
```

```
> bench::mark(f3(url), f2(url), f1(url), iterations = 20)
# A tibble: 3 x 14
  expression      min     mean   median      max `itr/sec`   mem_alloc  n_gc n_itr total_time result
  <chr>      <bch:tm> <bch:tm> <bch:tm> <bch:tm>     <dbl>   <bch:byt> <dbl> <int>   <bch:tm> <list>
1 f3(url)    15.103ms 16.483ms 16.416ms 19.542ms      60.7 131872.000B     0    20  329.658ms <xml_~
2 f2(url)    71.602ms 78.589ms 78.756ms 86.607ms      12.7 139656.000B     0    20 1571.781ms <xml_~
3 f1(url)    18.405ms 20.738ms 20.202ms 30.665ms      48.2    704.000B     0    20  414.760ms <xml_~
# ... with 3 more variables: memory <list>, time <list>, gc <list>
```

My understanding of the typical use-case is different URLs.

**Comment by MattCowgill** [comment]
Hmm OK if the difference is purely caching then I guess there's no need to make the change. Thanks all.
