### ISSUE TITLE
Contribute functions that tidy flat format data from the ABS' SDMX-JSON API

### ISSUE THREAD

**Issue by Annabel-Kennedy** [MattCowgill/readabs#147]
Good afternoon Matt,

I would love to contribute a collection of functions to your package, which were created by Abasi Latcham (@baslat) and myself. These functions ingest and tidy flat format data from the ABS' SDMX-JSON API. 

**There are a total of 7 functions, which are briefly outlined below:**

Exported functions:
- `abs_api` takes the API URL as its only parameter and returns a tidy tibble of the data queried. Both the ABS.Stat URL structure and the new API URL structure (as outlined on api.gov.au) is accepted. The following parameters would just need to be included in the URLs to organise the data in the flat view and JSON format: _dimensionAtObservation=allDimensions_ (for the ABS.Stat SDMX-JSON API) and _format=jsondata&dimensionAtObservation=AllDimensions_ (for the new API). 
- `abs_clipboard` assigns a really long URL (4087+ characters) to a variable, which gets around the RStudio console’s maximum string input of 4087 characters.
- `unique_chars` takes the results of an API call and shows you all the unique values for all character columns. (Useful to inform filtering, plotting etc.)

Helper functions:
- `abs_tidy_data` tidies the raw data queried using the ABS’ API and returns a tibble.
- `abs_split_url` splits one large URL into smaller URLs to increase efficiency.
- `abs_split_variables` splits each dimension in the API’s data key into batches with a maximum of 50 dimension members each.
- `abs_join` is a unique join function that helps to tidy the data.

**`abs_api` examples:**
ABS.Stat SDMX-JSON API URL:
```
old_url <- “http://stat.data.abs.gov.au/sdmx-json/data/ALC/all/all?startTime=2000&endTime=2016&dimensionAtObservation=allDimensions”
abs_api(old_url)
```

New API URL:
```
new_url <- “https://api.data.abs.gov.au/data/ABS,RES_DWELL/all?startPeriod=2019-Q4&endPeriod=2020-Q1&format=jsondata&dimensionAtObservation=AllDimensions”
abs_api(new_url)
```

These functions are explained in greater detail in the actual documentation of the code, all of which will be included in a pull request. Thank you.

Kind regards,
Annabel Kennedy

**Comment by MattCowgill** [comment]
@Annabel-Kennedy 
Hi Annabel,
This is wonderful! The timing on this is excellent as well - I had just been thinking I should write some function(s) that make it easier to work with the new API data. 

My only questions are:

- Are all the functions above exported?
- Would you consider renaming some functions? For example, the readabs package already has a (non-exported/internal) function called `tidy_abs()` that takes the ABS time series spreadsheets and tidies them up. Could be confusing.

Thanks very much, I'd definitely welcome a pull request along these lines

**Comment by MattCowgill** [comment]
also re: the key function, would you consider renaming `abs_api()` to `read_abs_api()` or similar? I feel like that would be more consistent with other functions in the package

**Comment by Annabel-Kennedy** [comment]
@MattCowgill 
Hi Matt,

Changing `abs_api()` to `read_abs_api()` sounds like a great idea and I'm very happy to change the names of any of the other functions (including `abs_tidy_data()`).

Currently only the first three functions are exported (`read_abs_api()`, `abs_clipboard()` and `unique_chars()`) as these are the only functions the user interacts with. Again, I'm happy for this to change as well though.

Thanks,
Annabel

**Comment by MattCowgill** [comment]
Thanks very much @Annabel-Kennedy. Maybe `tidy_api_data()` would be clearer? Not a huge deal for a non-exported function, but will still help those of us who work on the package to distinguish between the difference functions. 

Thanks again, I'm really excited about this.

**Comment by Annabel-Kennedy** [comment]
No problem @MattCowgill! I will make that change now. 

Thanks,
Annabel

**Comment by RichardScottOZ** [comment]
Thanks to everybody, btw!

**Comment by MattCowgill** [comment]
Unfortunately I believe this won't work with the ABS' revised API :( 

If I've got this wrong, someone please alert me/re-open the issue
