### ISSUE TITLE
get data by vintage

### ISSUE THREAD

**Issue by mcooganj** [MattCowgill/readabs#149]
the package is awesome! thanks. is there a way to get data by vintage? 

i've been looking and this seems (rightly) focused on getting the most recent data.

It would be awesome to be able to put in a series id and get all the various vintages of data.

**Comment by MattCowgill** [comment]
Thanks very much @mcooganj! Glad to hear you're liking the package.

Unfortunately not, at this stage. The core `read_abs()` function is built around an ABS API called the Time Series Directory. The TSD only allows us to get the URLs of the most recent release of a given time series. It would be possible to write a function to fetch previous vintages, but it would need to be implemented in a different way to `read_abs()` and is not on my short list at the moment. I agree it would be useful, but I don't have time right now.

Thanks again
