### ISSUE TITLE
Issue downloading quarterly employment data

### ISSUE THREAD

**Issue by melville1808** [MattCowgill/readabs#156]
```
 library(readabs)
read_abs(cat_no = "6202.0")
```
works as expected.

However, 
```
read_abs(cat_no = "6291.0") #quarterly employment data
```
returns an error:

>  Error in .f(.x[[i]], ...) : 
>   Cannot find valid entry for cat_no  in the ABS Time Series Directory.Check that the cat. no. is correct, and that it contains time series spreadsheets (not data cubes). 

Looking at the website, it looks like this was moved around when they updated the website.

**Comment by MattCowgill** [comment]
Hi @melville1808, try:
`readabs::read_abs("6291.0.55.001")`

The full catalogue number is, unfortunately, required.

Please note there is currently an issue with this catalogue number. Some tables aren't showing up in the Time Series Directory, the API that `read_abs()` queries. I have contacted the ABS about this and they're on it. I'll update this issue when the problem has been fixed.

**Comment by melville1808** [comment]
Thank you!

**Comment by MattCowgill** [comment]
FYI @melville1808 the ABS tells me this issue is now fixed (though I haven’t had a chance to test yet)

**Comment by MattCowgill** [comment]
Hi @melville1808 I think this is resolved now. It's slow but works.
