### ISSUE TITLE
ABS Quarterly Capital Expenditure Series Failing Again

### ISSUE THREAD

**Issue by MacroDave** [MattCowgill/readabs#157]
Hi Matt, the ABS have broken the quarterly CAPEX survey again. Same issue as last time, the shorter named series work and the longer named ones fail :-(

library(readabs)
ABS_Cons<- read_abs(series_id = "A3515968F") #WORKS
ABS_Acco<- read_abs(series_id = "A124798779V") #FAILS

**Comment by MattCowgill** [comment]
Blergh. Thanks for letting me know.

**Comment by MattCowgill** [comment]
I've contacted the ABS @MacroDave to try and get them to fix this. Thanks for letting me know.

**Comment by MattCowgill** [comment]
the ABS tells me this issue is now fixed @MacroDave but I haven’t had a chance to test yet

**Comment by MacroDave** [comment]
Yep, fixed again

**Comment by AdamElderfield** [comment]
Hi,

I am not sure if this is related, but read_abs(cat_no = "5625.0") doesn't seem to be working - it is pulling a table that ends in Dec 2020.

`
read_abs(cat_no = "5625.0") %>% 
filter(series_id =="A124792377V") %>%
 tail()

table_no sheet_no table_title date       series value series_type data_type collection_month frequency series_id
  <chr>    <chr>    <chr>       <date>     <chr>  <dbl> <chr>       <chr>     <chr>            <chr>     <chr>    
1 09_curr~ Data1    Table 9. A~ 2019-09-01 Actua~ 17622 Original    FLOW      3                Quarter   A1247923~
2 09_curr~ Data1    Table 9. A~ 2019-12-01 Actua~ 18743 Original    FLOW      3                Quarter   A1247923~
3 09_curr~ Data1    Table 9. A~ 2020-03-01 Actua~ 15259 Original    FLOW      3                Quarter   A1247923~
4 09_curr~ Data1    Table 9. A~ 2020-06-01 Actua~ 16888 Original    FLOW      3                Quarter   A1247923~
5 09_curr~ Data1    Table 9. A~ 2020-09-01 Actua~ 15261 Original    FLOW      3                Quarter   A1247923~
6 09_curr~ Data1    Table 9. A~ 2020-12-01 Actua~ 16994 Original    FLOW      3                Quarter   A1247923~
`

Where passing the series ID directly pulls the updated table.

`
read_abs(series_id = "A124792377V") 
%>% tail()

table_no sheet_no table_title date       series value series_type data_type collection_month frequency series_id
  <chr>    <chr>    <chr>       <date>     <chr>  <dbl> <chr>       <chr>     <chr>            <chr>     <chr>    
1 01_curr~ Data1    Table 1. A~ 2020-06-01 Actua~ 16888 Original    FLOW      3                Quarter   A1247923~
2 01_curr~ Data1    Table 1. A~ 2020-09-01 Actua~ 15261 Original    FLOW      3                Quarter   A1247923~
3 01_curr~ Data1    Table 1. A~ 2020-12-01 Actua~ 17090 Original    FLOW      3                Quarter   A1247923~
4 01_curr~ Data1    Table 1. A~ 2021-03-01 Actua~ 14762 Original    FLOW      3                Quarter   A1247923~
5 01_curr~ Data1    Table 1. A~ 2021-06-01 Actua~ 18219 Original    FLOW      3                Quarter   A1247923~
6 01_curr~ Data1    Table 1. A~ 2021-09-01 Actua~ 17269 Original    FLOW      3                Quarter   A1247923~
`

Apologies if this has been covered elsewhere, I did a search but couldn't find a solution. 

Adam
