### ISSUE TITLE
Sheet names have changed in Weekly Payroll Jobs and Wages - Indexes by Sub-state regions

### ISSUE THREAD

**Issue by hamgamb** [MattCowgill/readabs#175]
Hi Matt

``` r
readabs::read_payrolls(series = "sa3_jobs", path = "data-raw")
#> File downloaded in data-raw/6160055001_DO005.xlsx
#> Error in read_payrolls_local(cube_path = cube_path, sheet_name = sheet_name, : Could not find a sheet called 'Payroll jobs index-SA3' in the payrolls workbook data-raw/6160055001_DO005.xlsx. Sheets present are: SA4, SA3, GCCSA
```

<sup>Created on 2021-11-10 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

The ABS seem to have changed the names for the sheets in the sub-state payroll indexes in todays release. 

Payroll jobs index-SA4 is now SA4 
Payroll jobs index-SA3 is now SA3. 

https://github.com/MattCowgill/readabs/blob/aed7692af53ceb9ce27b8177ec7d740a7d01f76f/R/read_payrolls.R#L98-L104

I guess this isn't as simple as changing the above, because you probably want to maintain the ability to download the cube from the previous release. 

https://github.com/MattCowgill/readabs/blob/aed7692af53ceb9ce27b8177ec7d740a7d01f76f/R/read_payrolls.R#L78-L81

**Comment by MattCowgill** [comment]
Thanks @hamgamb thanks - I’d seen that as my daily R CMD check failed. I’ll try to fix tonight. Not sure why the ABS does this sort of thing.

**Comment by daviddiviny** [comment]
It is good you don't take it personally.

**Comment by MattCowgill** [comment]
Fixed now @hamgamb. I won't update on CRAN until I've fixed a few other issues (likely 1-2 weeks) but it's fixed in the Github version.
