### ISSUE TITLE
Changes to Excel file format on the ABS website

### ISSUE THREAD

**Issue by hamgamb** [MattCowgill/readabs#179]
Hi Matt! 

I'm sure you already know. The ABS is changing to .xlsx (progressively) for time series spreadsheets.

Could the below be changed to `pattern = "\\.(xls|xlsx)$"`. I did some quick tests and it seemed to work. 

https://github.com/MattCowgill/readabs/blob/47c73f43a12e63821df5c0b51f8b38d3959d4a76/R/read_abs_local.R#L113

**Comment by MattCowgill** [comment]
Hi @hamgamb, yes please! I thought I’d found all the xls-specific code but looks like you’ve found some more. That same snippet might be in read_abs_local() as well - could you have a look? (I’m on a train sans laptop or I would)

Could you put through a PR? Thanks so much

**Comment by MattCowgill** [comment]
(I’d make this change but I’m out for the day without my laptop)

**Comment by hamgamb** [comment]
Happy to do so. Likely after lunch
