### ISSUE TITLE
Could not download ABS payrolls data.

### ISSUE THREAD

**Issue by JamesAngus** [MattCowgill/readabs#201]
`read_payrolls("empsize_jobs")`
Error in read_payrolls("empsize_jobs") : 
  Could not download ABS payrolls data.

**Comment by MattCowgill** [comment]
@JamesAngus i see you closed this issue. Did you resolve your problem?

**Comment by JamesAngus** [comment]
> @JamesAngus i see you closed this issue. Did you resolve your problem?

Yeah all good, my mistake
