### ISSUE TITLE
Package is looking to download xls files

### ISSUE THREAD

**Issue by yashiro-tar** [MattCowgill/readabs#234]
Matt, 
Thanks for the package. 
Running  _all_wpi <- read_abs("6345.0")_ 

I get Error in FUN(X[[i]], ...) : 
  cannot coerce type 'closure' to vector of type 'character'

Upon checking, I can see that the package is looking for xls files (trying URL 'https://www.abs.gov.au/statistics/economy/price-indexes-and-inflation/wage-price-index-australia/latest-release/634501.xls') and as you know, ABS does not have those anymore. 

I could not find any functions that would let me update the list of available files or something like that..

I tried following as well with the same results:

lfs_1 <- read_abs("6202.0", tables = 1)
wpi_cons <- read_abs(series_id = c("A2603019J"))

**Comment by MattCowgill** [comment]
Hi, thanks for opening the issue. Can you please confirm what version of the package you're using? @yashiro-tar 

`read_abs()` doesn't rely on an internal file list. Instead, it queries an ABS API (the Time Series Directory) looking for the file(s) you've requested. Unless something has changed in that API, it's difficult for me to understand how this problem could arise. 

I'm on holiday without my laptop at the moment so can't test or fix this until next week

**Comment by MattCowgill** [comment]
Ok the problem seems to be with the ABS TSD. I'll raise it with the ABS and will update this issue when they've fixed it.

**Comment by MattCowgill** [comment]
Note to self: the query above uses this TSD request: https://ausstats.abs.gov.au/servlet/TSSearchServlet?catno=6345.0&ttitle=1

It returns an invalid link to an .xls file. This is not the only affected catalogue number. I've contacted the ABS.

**Comment by MattCowgill** [comment]
The PR linked above provides a workaround to the ABS bug. If/when it passes all the tests, I'll merge the PR and then this should be fixed. 

Working off my iPad via Posit Cloud so this is an inefficient process...

**Comment by yashiro-tar** [comment]
> Hi, thanks for opening the issue. Can you please confirm what version of the package you're using? @yashiro-tar
> 
> `read_abs()` doesn't rely on an internal file list. Instead, it queries an ABS API (the Time Series Directory) looking for the file(s) you've requested. Unless something has changed in that API, it's difficult for me to understand how this problem could arise.
> 
> I'm on holiday without my laptop at the moment so can't test or fix this until next week

Sorry to bother you on your vacation.... and thank you for checking... it is not important anymore but I am using the latest version.

**Comment by MattCowgill** [comment]
No worries, thanks for opening the issue @yashiro-tar, I appreciate the heads up

**Comment by MattCowgill** [comment]
update: the ABS has responded, they're looking into the issue. 

I can't merge my PR now as there are other issues that need to be fixed. It's too difficult on my iPad, will fix on Sunday.

**Comment by yashiro-tar** [comment]
Thank you so much..

**Comment by MattCowgill** [comment]
Update: the ABS has now rectified the issue. Your code should work now @yashiro-tar, without updating the package. I will still put through the PR linked above next week, as this will help guard against similar issues in the future.
