### ISSUE TITLE
Closure issue?

### ISSUE THREAD

**Issue by jasemurphy** [MattCowgill/readabs#243]
Hi Matt,

I can't get any series to download, here's the error message it's returning for my attempt to get lending indicators. 2023.09.0+463, running on a macbook air m1

```
fstcore package v0.9.14
(OpenMP was not detected, using single threaded mode)
Finding URLs for tables corresponding to ABS catalogue 5601.0
Attempting to download files from catalogue 5601.0, Lending Indicators
trying URL 'https://www.abs.gov.au/statistics/economy/finance/lending-indicators/latest-release/560103.xlsx'
trying URL 'https://www.abs.gov.au/statistics/economy/finance/lending-indicators/latest-release/560103.xls'
Error in FUN(X[[i]], ...) : 
  cannot coerce type 'closure' to vector of type 'character'
```

THANKS for having a look. :)

**Comment by jasemurphy** [comment]
I saw your reply to the other guy, hope the ABS fix this soon.

**Comment by MattCowgill** [comment]
For anyone else encountering this, the other issue Jason mentioned is here: https://github.com/MattCowgill/readabs/issues/242#issuecomment-1849097606 

There is a problem on the ABS side. While we wait for a fix from the ABS (it is unrelated to the readabs package itself), there is a temporary workaround that involves specifying the data date, as in the examples linked above.
