### ISSUE TITLE
Allow read_abs_local to read multiple sheets

### ISSUE THREAD

**Issue by wfmackey** [MattCowgill/readabs#29]
Allow `read_abs_local` to read/tidy multiple sheets. Eg where `read_abs("3220.0")` creates a folder in `data`/`ABS` with a number of separate spreadsheets, `read_abs_local("3220.0")` should work.

**Comment by MattCowgill** [comment]
I'll add this @wfmackey. In the meantime, if you leave the 'filenames' argument blank and specify the path, `read_abs_local()` will attempt to import and tidy all .xls sheets in that directory

**Comment by MattCowgill** [comment]
feature added in https://github.com/MattCowgill/readabs/commit/c4523a2fef6c6f87a339d5c51cb98b3ec6f0d8f2

**Comment by wfmackey** [comment]
Niceeee

On 27 May 2019, at 8:58 am, Matt Cowgill <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #29<https://github.com/MattCowgill/readabs/issues/29>.

**Comment by MattCowgill** [comment]
log off @wfmackey
