### ISSUE TITLE
unable to download certain abs time series

### ISSUE THREAD

**Issue by hamgamb** [MattCowgill/readabs#30]
attempting to download all retail trade time series spreadsheets (8501.0) using read_abs("8501.0") get the following:
Finding filenames for tables from ABS catalogue 8501.0
Document is empty
Error: 1: Document is empty

specifying tables works except for tables 5-10 which are chain-volume measures. 

Assume this is a problem on the abs side?

**Comment by MattCowgill** [comment]
Thanks @hamgamb I’ll look into this later today

**Comment by MattCowgill** [comment]
Hi @hamgamb - as you suspected, this is a problem with the ABS Time Series Directory API. I have contacted them and asked them to fix it. Sorry about this.

**Comment by MattCowgill** [comment]
FYI @hamgamb - I'm still waiting on a response from the ABS. They have fixed previous problems with the Time Series Directory, but it sometimes takes a little while. I'll update you when this is fixed.

**Comment by hamgamb** [comment]
thanks @MattCowgill - appreciate it

**Comment by MattCowgill** [comment]
Hi @hamgamb I have an update coming later today that will fix this problem

**Comment by MattCowgill** [comment]
Hi @hamgamb, I just spoke to people at the ABS who assure me they are working on this problem.

**Comment by MattCowgill** [comment]
Hi @hamgamb, the ABS has just fixed some things on their end. 8501 table 5 (etc) now works. `read_abs("8501.0")` doesn't currently work, but I will fix this. Please ensure you're running the latest version, 0.3.1.
