### ISSUE TITLE
Function to separate series

### ISSUE THREAD

**Issue by daviddiviny** [MattCowgill/readabs#34]
This is a great package, that has already saved me a bunch of time. 

In using it though, we find the need to separate `series` into multiple columns (as set out in the below code). 

```r
tidy_abs_data <- read_abs("6291.0.55.003", tables = 7) 

lfs_major_occ_gender <- tidy_abs_data %>% 
  select(qtr = date,
         value) %>% 
  mutate(series = str_squish(gsub(">", " ", series, fixed = TRUE))) %>% 
  separate(series, into = c("major_group_name", "variable", "gender"), sep = ";") %>%
  mutate(major_group_name = str_squish(major_group_name),
         variable  = str_squish(variable),
         gender = str_squish(gender)) %>% 
  mutate(major_group_name = ifelse(grepl("Employed", major_group_name), "All occupations", major_group_name)) %>%
  filter(major_group_name != "All occupations") %>% 
  filter(gender != "Persons") %>%
  filter(variable != "Employed total")
```
I'm happy to help out with a solution, but wanted to check you hadn't already tried this and bashed your head into a wall.

**Comment by MattCowgill** [comment]
Hi @daviddiviny, thanks very much. Yes, you're right, the `series` column does often need to be further separated into multiple columns. I would love to add a function to do this, but I'm not sure how to do it in a way that will handle the different formats that are included in ABS time series descriptions.

In your example, the series have three components. Sometimes there is only one component; sometimes there are more than three components. Sometimes the third component will be sex (as in your example), sometimes it will be something else. I don't know how to write a function that will split series into new columns and handle this diversity.

What do you have in mind? I'm definitely open to solutions here! I would prefer a new function rather than a modification of an existing function.

Thanks again

**Comment by daviddiviny** [comment]
Okay, @ellisp and I might put our heads together. We are reading different ABS datasets into our data warehouse so will think about some solutions.

**Comment by MattCowgill** [comment]
hi @daviddiviny, have you had any further thoughts about this? I remain unsure it can be done in a way that can handle the variety of series names the ABS throws at us...

**Comment by daviddiviny** [comment]
Not yet. 
As a first step, I was going to try and have a look at the different series and see if there is any structure. 
A fallback solution would be a helper function that requires some user input on how they want to handle the column.

**Comment by MattCowgill** [comment]
Fair enough! I'm working on version 0.4.0 - it includes a function to get specific time series using their ABS IDs. I'll probably release this within the next week or two, so if you/we end up doing something with the series splitting it can go in the version after that

**Comment by daviddiviny** [comment]
Is there is a machine readable list of time series?

**Comment by MattCowgill** [comment]
Not that I'm aware of @daviddiviny. You can query the ABS time series directory API (https://www.abs.gov.au/websitedbs/D3310114.nsf/89a5f3d8684682b6ca256de4002c809b/0813090ddc7a5cfbca2575e100122678!OpenDocument) - that's how this package works under the hood. But I don't know of a way to get it to return a list of all series, you have to specify a catalogue number or some other identifier.

**Comment by daviddiviny** [comment]
This seems to work, but needs some more testing. Also it would be good to know if any series don't use ";" as their separator?

It allows the user to specify the column names. If not specified, then the column names will be series_1, etc. 

```r
library(stringr)
library(tidyr)
library(dplyr)

separate_series <- function(data, column_names = NULL, remove_totals = FALSE){
  #Minor data cleaning of series column
  data <- mutate(data,
                 series = str_extract(series, ".+(?= ;)"), #Extract everything before trailing ;
                 series = str_replace_all(series, pattern = ">", replacement = ""),
                 series = str_squish(series))
  #Filter totals if specified
  if(remove_totals){
    data <- filter(data,
                   !grepl("total", series, ignore.case = T))
  }
  # Determine number of ; separators
  n_seps <- max(str_count(data$series, ";"))
  # Determine number of columns
  n_columns <- n_seps + 1
  #create column names if not specified
  if(is.null(column_names)){
    column_names <- paste("series", 1:n_columns, sep = "_")
  }
  
  #Separate columns
  data_separated <- separate(data, series,
                             into = column_names,
                             sep = ";",
                             remove = FALSE,
                             fill = "left") %>% 
    mutate_at(.vars = vars(column_names), str_squish)
  
  
  #check for columns with NAS
  na_columns <- paste0(colnames(data_separated)[colSums(is.na(data_separated)) > 0],
                       collapse = ", ")

  if(na_columns != ""){warning(na_columns, " column(s) have NA values.", call. = TRUE)}
  return(data_separated)
}
```
Some examples. 

```r
motor_vehicles <- read_abs("9314.0") %>%
  separate_series()

lfs_major_occ_gender <- read_abs("6291.0.55.003", tables = 7) %>%
  separate_series(column_names = c("major_group_name", "variable","gender"))

```

**Comment by MattCowgill** [comment]
Hi @daviddiviny thanks so much for this. I'll work through it properly later today and test it with some other ABS series. Looks promising, cheers

**Comment by daviddiviny** [comment]
My pleasure! Let me know if you find any bugs or series with which it doesn't work.

**Comment by MattCowgill** [comment]
Hi @daviddiviny, this is really cool! 

I guess the only problem is that where you have some series that have two parts, and some that have three, the newly created columns might end up being a mix of variables, for example:

`lfs <- read_abs("6291.0.55.003", 5, retain_files = FALSE) %>%
  separate_series()`

Then look at:

`unique(lfs$series_2)`

The result is a mix of industries (most series) and geographies, for series where series_1 is NA. I think this is OK, particularly as you've given users a warning.

I'm inclined to include the function in the next release (0.4.0, still haven't finalised). Users will have to invoke it themselves as a separate step to `read_abs()` as in our examples above. What do you think?

Thanks again for this. The `fill = "left"` option in `separate()` is really clever here.

**Comment by daviddiviny** [comment]
Thanks @MattCowgill. Seriously, my pleasure. Nous gets a lot of value from Grattan's work (R packages + reports) so very happy to give back in a v. small way. 

I will try and do the Roxygen etc and maybe some examples for the vignette over the long weekend.

**Comment by MattCowgill** [comment]
Cheers David. The new version (still WIP) is in the 'dev' branch FYI, if you're doing a pull request.

**Comment by daviddiviny** [comment]
Thanks @MattCowgill - that was fun!  I'm going to close this issue. Do you mind adding me as a contributor to the Description as well?

**Comment by MattCowgill** [comment]
of course, will do

**Comment by MattCowgill** [comment]
OK to use your Nous email in the DESCRIPTION file, @daviddiviny? It will be visible on CRAN, etc.

**Comment by daviddiviny** [comment]
Yep, that's fine.
