### ISSUE TITLE
add ability to download individual time series based on their unique ABS ID

### ISSUE THREAD

**Issue by MattCowgill** [MattCowgill/readabs#4]
having trouble with the XML queries for individual series IDs.

For example, this query of the time series directory fails: http://ausstats.abs.gov.au/servlet/TSSearchServlet?sid=A84423127L

While this returns valid XML metadata including the A84423127L series: http://ausstats.abs.gov.au/servlet/TSSearchServlet?sid=A84423127*

I contacted the ABS on 2018-01-11 to ask why the specific query doesn't work while the general query does work.

**Comment by MattCowgill** [comment]
can use the direct URL for this, eg. http://www.ausstats.abs.gov.au/ausstats/meisubs.nsf/GetTimeSeries?OpenAgent&sid=A2325846C, see http://www.abs.gov.au/AUSSTATS/abs@.nsf/97adb482c0aba769ca2570460017d0e7/15d1d9943893067dca2572ec00157f40!OpenDocument

**Comment by MattCowgill** [comment]
direct URL method working for most series but also throwing errors for some, incl. the same A84423127L (Labour Force, Employed Total, Persons, Trend). Shelving this until/unless the ABS responds to my query.

**Comment by MattCowgill** [comment]
if the ABS can't fix this, try a multi-stage process, given a series ID:

- try the direct URL;
- if that fails, query the time series directory with the last character (or two?) trimmed and a * in place;
- if that fails, trim another character or two?
- then return error

**Comment by MattCowgill** [comment]
might not work because the direct URLs return TRUE with RCurl::url.exists() even when there's an error; might need to go straight to the time series directory stage

**Comment by MattCowgill** [comment]
can use httr::GET() to check whether the content of a URL is an Excel document or not

**Comment by HughParsonage** [comment]
Using the headers, rather the entire file, might be better. Something like this should be better than using `httr::GET`

```r
url_is_excel <- function(url) {
  if (url_http_error <- httr::http_error(url)) {
    stop("The following URL had error code ", url_http_error, ".\n\t", 
         url)
  }
  Header <- httr::HEAD(url)
  Content <- Header[["Headers"]][["content-type"]]
  ## Excel 2007 and after (.xlsx), and
  ## Excel BIFF, e.g. 2003 (.xls) 
  Content %in% c("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",  
                 "application/vnd.ms-excel")
}

```

**Comment by MattCowgill** [comment]
Excellent, this works, thanks @HughParsonage

**Comment by MattCowgill** [comment]
email from the ABS on 2018-2-21 indicating that they're going to fix the issue in the Time Series Directory I encountered above within the next week - I will wait to implement this feature until they've made the change. Might not need to use direct URLs as a fallback if the TSD API works.

**Comment by MattCowgill** [comment]
ABS has repaired the Time Series Directory, as of today. I will now add this feature.
