### ISSUE TITLE
Add argument drop_NAs to separate_series

### ISSUE THREAD

**Issue by zerogetsamgow** [MattCowgill/readabs#40]
Would the separate_series function be improved by adding an argument remove_NAs similar to remove_totals?

If remove_NAs = TRUE, then rows with NA in the separated series columns would be filtered out.

For example, read_abs("6291.0.55.003", tables = 5) %>% separate_series() separates the series variable into three columns with data on (1) jurisdiction, (2) ANZSIC division title and (3) whether the value is counting persons 'Employed full-time', 'Employed part-time' and 'Employed total'. If remove_totals = TRUE rows with 'Employed total' are removed. 

However, the data also contains rows aggregating employed persons across all ANZSIC division titles in each jurisdiction (eg series_ID = A84601054W). As these are represented in the series variable as "Australia; Employed full-time" it is separated across the three generated series as NA, "Australia" and "Employed full-time". Adding the argument remove_NAs, which might default to TRUE, could remove these rows.

**Comment by MattCowgill** [comment]
I like it, @zerogetsamgow! What do you think, @daviddiviny? I'd be happy to add this in

**Comment by daviddiviny** [comment]
Yes, but I think it should probably default to FALSE.

**Comment by MattCowgill** [comment]
agreed @daviddiviny

**Comment by MattCowgill** [comment]
Thanks @zerogetsamgow and @daviddiviny, I’ve added this now. I won’t update CRAN until there’s a few other changes.
