### ISSUE TITLE
Use R_READABS_PATH as a cache 

### ISSUE THREAD

**Issue by HughParsonage** [MattCowgill/readabs#49]
We could use the path `R_READABS_PATH`:

  1. to cache the results of `read_abs` as a [`.fst`](https://github.com/fstpackage/fst) file, to improve performance, and perhaps harness the random-access features of that file. 
  2. using the modification time, the maximum date in the file, or, say, a file containing the MD5 hashes, to determine whether the local file needs to be updated when reading. (#46 )

The eventual goal is for the user to just type `read_abs("6345.0")` and for `readabs` to:

  1. if the file exists and is up-to-date---simply read it immediately
  2. if the file does not exist or is not up-to-date---download the `.xls` file, tidy it, and then read the tidy files immediately on subsequent occasions.

without the user having to tradeoff performance against accuracy/recency.

**Comment by MattCowgill** [comment]
I like the idea @HughParsonage! 

The ABS Time Series Directory (the crummy old API that the package is built around) does return a value for "Frequency"  and "ProductReleaseDate" (which isn't always the same as the modification date) for each time series. We could use those to figure out whether the file is (likely to be) up to date

**Comment by HughParsonage** [comment]
Cool. Could I get push access to this repo? Makes it easier to collab rather than messing about with forks. Don't need master branch push permission.

**Comment by MattCowgill** [comment]
Done

Let me know what you're thinking!
