### ISSUE TITLE
read_abs fails on split DNS network

### ISSUE THREAD

**Issue by OscarLane** [MattCowgill/readabs#55]
I work at an organisation that runs a split DNS network, which means that read_abs will fail by default. This is due to the reliance on curl's nslookup function. The error looks like this, though you probably won't be able to reproduce this error without a similar network setup:

``` R
x <- read_abs(cat_no = "6202.0")
Error in read_abs(cat_no = "6202.0") : 
  R cannot access the ABS website. `read_abs()` requires access to the ABS site.
         Please check your internet connection and security settings.
```

I've managed to fix this by removing lines 151-156 of read_abs.R:

``` R
  if(is.null(curl::nslookup("abs.gov.au", error = FALSE))){

    stop("R cannot access the ABS website. `read_abs()` requires access to the ABS site.
         Please check your internet connection and security settings." )

  }
```

However, I understand we probably still want the package to test for internet connectivity! A solution like [this](https://stackoverflow.com/questions/5076593/how-to-determine-if-you-have-an-internet-connection-in-r) works in the split DNS environment. I wonder if we could consider changing it to be like that or something similar that doesn't rely on curl?

**Comment by MattCowgill** [comment]
Hi @OscarLane, thanks for bringing this to my attention and for testing a fix. I'm happy to include this change. As a nice side effect, this code looks to be quicker, too:

``` r
library(microbenchmark)

havingIP <- function() {
  if (.Platform$OS.type == "windows") {
    ipmessage <- system("ipconfig", intern = TRUE)
  } else {
    ipmessage <- system("ifconfig", intern = TRUE)
  }
  validIP <- "((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)[.]){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)"
  any(grep(validIP, ipmessage))
}

microbenchmark(curl::nslookup("abs.gov.au", error = FALSE),
               havingIP)
#> Unit: nanoseconds
#>                                         expr    min       lq      mean   median
#>  curl::nslookup("abs.gov.au", error = FALSE) 500968 541991.5 722740.20 599325.5
#>                                     havingIP     19     25.0    216.36    182.5
#>        uq      max neval cld
#>  680709.5 11046911   100   b
#>     287.5     3417   100  a
```

<sup>Created on 2019-11-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Would you like to do a pull request, or do you want me to make this change?

**Comment by MattCowgill** [comment]
Actually - I just tried this `havingIP()` function while disconnected from the internet and it still returned 'TRUE'. This is obviously not ideal...

So I'm definitely open to replacing `curl::nslookup()` with something that will work in your type of environment (and others), but this code may not do the trick

**Comment by MattCowgill** [comment]
`pingr::is_online()` is quick and looks like it might work in your environment (though I can't test this).

**Comment by HughParsonage** [comment]
Your benchmark is simply testing the symbol not the function.

**Comment by MattCowgill** [comment]
Ah yes, silly me. Thanks Hugh.

**Comment by MattCowgill** [comment]
Running an actual benchmark (thanks @HughParsonage) shows the suggested function is quite a bit slower (and also is not satisfactory regardless of speed, see above)

``` r
library(microbenchmark)

havingIP <- function() {
  if (.Platform$OS.type == "windows") {
    ipmessage <- system("ipconfig", intern = TRUE)
  } else {
    ipmessage <- system("ifconfig", intern = TRUE)
  }
  validIP <- "((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)[.]){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)"
  any(grep(validIP, ipmessage))
}

microbenchmark(curl::nslookup("abs.gov.au", error = FALSE),
               havingIP())
#> Unit: microseconds
#>                                         expr      min        lq      mean
#>  curl::nslookup("abs.gov.au", error = FALSE)  547.468  594.5585  860.4498
#>                                   havingIP() 7858.420 8594.3160 9656.6090
#>     median        uq      max neval cld
#>   848.6385   917.952 10425.45   100  a 
#>  9291.4705 10242.060 27698.70   100   b
```

<sup>Created on 2019-11-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by OscarLane** [comment]
Thanks for looking into this Matt.

So `pingr::is_online` looks like a solution, except that the first method tried by it (`my_ip(method = "dns"`)  fails and takes about 12 seconds on my system to realise that it can't contact the DNS server.

`my_ip(method = "https")` and `apple_captive_test()` both work quickly, so if I were making the change I'd choose one of those. Don't have git on this machine, but happy to make a PR when I'm not at work.

**Comment by HughParsonage** [comment]
You could do `is.null(curl::nslookup("abs.gov.au", error = FALSE)) && havingIP()` to retain the fast track while not erroring spuriously

**Comment by MattCowgill** [comment]
Thanks @HughParsonage. I've made that change in the `fix-internet-check` branch now. 

@OscarLane if you could test `read_abs()` from the `fix-internet-check` branch in your work environment to see if it fixes the issue, I'd appreciate it

**Comment by OscarLane** [comment]
I'm testing a new method in my fork: https://github.com/OscarLane/readabs/commit/f6d5806ae70e7718a4e5930ff95ba5c6a69e53be

Will try this at work tomorrow and make a pull request if everything works fine from there.
