### ISSUE TITLE
ABS Beta website support

### ISSUE THREAD

**Issue by preshantjoseph** [MattCowgill/readabs#61]
Hi 

I was wondering whether this package will work on the ABS beta website (https://beta.abs.gov.au/)?

My understanding is that the ABS will be shifting to the new website in Mid 2020.

Thanks

Preshant

**Comment by MattCowgill** [comment]
Hi Preshant, 
Very good question and unfortunately not one I know the answer to. 
The ABS hasn't yet been clear about:
1) what the downloadable files will look like on the new website (they're not accessible on the beta version); and
2) whether existing APIs including the Time Series Directory API used by this package will continue. 

I have been in touch with them about this. If it is possible to make the package compatible with the new site, I'll do so. 

This is a risk though - it's possible that code you write now will not work in a year's time if the ABS cuts off the existing APIs without replacing them with something similar.

**Comment by daviddiviny** [comment]
More [detail on the API ](https://staging.api.gov.au/service/bdaddcd8-a569-4dca-9424-e31f0de8f454) has been released today.

**Comment by MattCowgill** [comment]
Thanks @daviddiviny

**Comment by MattCowgill** [comment]
@preshantjoseph the website transition has now happened and {readabs} continues to work well.
