### ISSUE TITLE
read_abs not getting latest data

### ISSUE THREAD

**Issue by AEdlerfi** [MattCowgill/readabs#62]
Hi,

When I run:
`read_abs(cat_no = "5206.0", tables = 6)`

I get the data consistent with the September release of the National Accounts, not the December. This only seems to be happening with table 6, all other tables from the same catalogue seem OK.

The below reproduces the error:
` 
data.frame(last_date_table_6 =xts::last(unique(read_abs(cat_no = "5206.0", tables = 6)$date)),last_date_table_1 =xts::last(unique(read_abs(cat_no = "5206.0", tables = 1)$date)))
 
`
last_date_table_6 should be 2019-09-01

Thanks

Adam

**Comment by MattCowgill** [comment]
Hi Adam,
Thanks for bringing this to my attention. This appears to be an error on the ABS end. `read_abs()` uses an ABS API, the Time Series Directory, to find the latest data and its URL(s) for download. When I manually go to the page in the Directory corresponding to this catalogue + table number (https://ausstats.abs.gov.au/servlet/TSSearchServlet?catno=5206.0&ttitle=6&pg=4), I can see that the latest ProductIssue is June 2019, the latest ProductReleaseDate is 2019-09-04.  As you mention, it does not appear to be an issue with other tables from this release.

I will contact the ABS and ask them to fix this problem. I'll let you know if/when they get back to me. Unfortunately there is nothing I can do in the meantime while we wait for them to fix the API.

Thank you
Matt

**Comment by AEdlerfi** [comment]
Thanks Matt - great package by the way. I know a lot of people who love it!

**Comment by MattCowgill** [comment]
Cheers Adam, I really appreciate that. I emailed the ABS this morning, will let you know when they get back to me. I suspect there may be a delay over the Christmas period.

**Comment by MattCowgill** [comment]
Hi @AEdlerfi, the ABS has now fixed this problem with the Time Series Directory. If you have any further problems please let me know.
