### ISSUE TITLE
6401.0 not working

### ISSUE THREAD

**Issue by MattCowgill** [MattCowgill/readabs#65]
On 2020-02-13, the ABS updated tables 13 and 14 of ABS 6401.0. 

Since then, queries of the ABS Time Series Directory for cat no 6401.0 only return entries corresponding to tables 13 and 14, not other tables: https://ausstats.abs.gov.au/servlet/TSSearchServlet?catno=6401.0

I have contacted the relevant person at the ABS and await a fix on their end. This is not a `readabs` fault.

**Comment by MattCowgill** [comment]
The ABS has now fixed this issue and created even bigger issues.

For example, if I go to this URL, I get a 404 error:
https://ausstats.abs.gov.au/servlet/TSSearchServlet?catno=6345.0&ttitle=1

Similarly, this returns a 404 error:
https://ausstats.abs.gov.au/servlet/TSSearchServlet?catno=6202.0&ttitle=1

These links worked before.

If I go to this URL, it returns an XML page as expected:
https://ausstats.abs.gov.au/servlet/TSSearchServlet?catno=6345.0

However, the information returned in that XML page is incorrect. For example, the URL the TSD XML lists for Table 1 is:
https://www.abs.gov.au/AUSSTATS/meisubs.nsf/lookupAttach/6345.0Time+Series+Spreadsheet13.11.191/$file/634501.xls

That link returns a 404 error.

I have contacted the ABS.

**Comment by daviddiviny** [comment]
I think the whole ABS website is broken. There are broken links on many downloads through the website.

**Comment by MattCowgill** [comment]
Yep, looks like that's right: https://twitter.com/ABSStats/status/1229905749679079424?s=20

A friend who works there tells me that issues like this are usually fixed around product release time (11:30am)

**Comment by MattCowgill** [comment]
appears to be fixed now
