### ISSUE TITLE
6333 not working

### ISSUE THREAD

**Issue by JoeFernando** [MattCowgill/readabs#69]
read_abs("6333.0", tables = 10)

Finding filenames for tables corresponding to ABS catalogue 6333.0
Error in .f(.x[[i]], ...) : 
  Cannot find valid entry for cat_no  in the ABS Time Series Directory

I feel this table is going to be accessed a lot.....pls help

**Comment by MattCowgill** [comment]
Hi @JoeFernando,
`readabs` can only load time series spreadsheets from the ABS. Unfortunately, 6333.0 is not released as a time series, all the tables in the cat. no. are 'data cubes'. You can see the distinction on the downloads tab for the release: https://www.abs.gov.au/AUSSTATS/abs@.nsf/DetailsPage/6333.0August%202019?OpenDocument

For reference, here is an image from the package vignette:

![image](https://user-images.githubusercontent.com/8002951/77612470-57ed0380-6f7c-11ea-8da7-bcadf87f57ff.png)

Sorry about that
