### ISSUE TITLE
Error for cat no 3301.0

### ISSUE THREAD

**Issue by jeauxlb** [MattCowgill/readabs#70]
Hi,

When I run
`data <- read_abs("3301.0")`
I get the error:
```Finding filenames for tables corresponding to ABS catalogue 3301.0
Error in .f(.x[[i]], ...) : 
  Cannot find valid entry for cat_no  in the ABS Time Series Directory.Check that the cat. no. is correct, and that it contains time series spreadsheets (not data cubes).
```

It seems that 3301.0 does has time series spreadsheets when I visit [the ABS website](https://www.abs.gov.au/AUSSTATS/abs@.nsf/DetailsPage/3301.02018?OpenDocument). Wondering if I'm missing something?

Example code given in the README works fine.

Thank you.

**Comment by MattCowgill** [comment]
Hi,
Unfortunately the ABS has not released the data in that catalogue number as a time series. They are instead formatted as "data cubes". You can see this on the page for the entry -- all the spreadsheets are "data cubes". https://www.abs.gov.au/AUSSTATS/abs@.nsf/DetailsPage/3301.02018?OpenDocument

I don't know why they've done this. I'll add it to my list of issues to raise with the ABS. Unfortunately the readabs package cannot currently be used to read data cubes, only time series (that are formatted as time series and entered in the ABS Time Series Directory).
