### ISSUE TITLE
read_abs() by series_id is importing double values

### ISSUE THREAD

**Issue by ch3lle82** [MattCowgill/readabs#73]
Hello,
When I try to import a bunch of ABS series IDs at the same time, if some series appear in multiple publications, then read_abs() will import the values twice into a single cell. Is there a way to import the longest unique series only? For example:

`# Function for extracting ABS series and transforming to a wide-form dataframe
dl_abs <- function(variables) { 
  df <- read_abs(series_id = variables) 
  rownames <- NULL
  df <- subset(df, select = c(date, series_id, value)) 
  df <- pivot_wider(df, names_from = "series_id", values_from = "value") 
  df <- df[order(df$date), ] 
}

# List of series to be imported
series <- c("A84423032W", "A84423060F", "A84423046K", "A84423027C")

# Dataframe of ABS series
x <- dl_abs(series)`

Thanks
Michelle

**Comment by MattCowgill** [comment]
Hi,
I think this is basically the same issue you raised last night (https://github.com/MattCowgill/readabs/issues/71). I'll fix the issue as soon as I can. In the meantime, I recommend that you get data by table rather than series_id. I included some example code in the other issue. 

Thanks,
Matt

**Comment by ch3lle82** [comment]
OK thanks Matt!
