### ISSUE TITLE
Issue with Cat 5302.0 - Table 10

### ISSUE THREAD

**Issue by mitchfscott** [MattCowgill/readabs#80]
Hi Matt,

I was trying to read in a listof tables from Cat 5302.0. Didn't have any issue apart from with Table 10. I tried calling the desired series using the table number and specific series ID but got the same error each time. 

The easiest way to replicate:
library(readabs)
df <- read_abs(cat_no = '5302.0', table = 10)

Error:
Finding filenames for tables corresponding to ABS catalogue 5302.0
Input is not proper UTF-8, indicate encoding !
Bytes: 0xA0 0x20 0x3B 0x3C
Error: 1: Input is not proper UTF-8, indicate encoding !
Bytes: 0xA0 0x20 0x3B 0x3C

**Comment by MattCowgill** [comment]
Hi, thanks for reporting this @mitchfscott. I'm not sure what's going on, I'll figure it out.

**Comment by MattCowgill** [comment]
Hi, FYI I'm still trying to figure out what's going on here. It's a weird issue. Sorry for the delay.

**Comment by MattCowgill** [comment]
OK there seems to be something weird with the file, but I found a workaround. Working on a fix now.

**Comment by MattCowgill** [comment]
Hi @mitchfscott, this table should work now. The problem wasn't with the readabs package per se, but I've managed to work around the issue. 

Please update the package using `devtools::install_github("mattcowgill/readabs")`. 

Then it works: 

``` r
readabs::read_abs("5302.0", 10)
#> Finding filenames for tables corresponding to ABS catalogue 5302.0
#> Attempting to download files from catalogue 5302.0, Balance of Payments and International Investment Position, Australia
#> Extracting data from downloaded spreadsheets
#> Tidying data from imported ABS spreadsheets
#> # A tibble: 20,252 x 12
#>    table_no sheet_no table_title date       series value series_type data_type
#>    <chr>    <chr>    <chr>       <date>     <chr>  <dbl> <chr>       <chr>    
#>  1 5302010  Data1    TABLE 10. … 1959-09-01 PRIMA…    11 Original    FLOW     
#>  2 5302010  Data1    TABLE 10. … 1959-09-01 PRIMA…     1 Original    FLOW     
#>  3 5302010  Data1    TABLE 10. … 1959-09-01 PRIMA…    10 Original    FLOW     
#>  4 5302010  Data1    TABLE 10. … 1959-09-01 PRIMA…     3 Original    FLOW     
#>  5 5302010  Data1    TABLE 10. … 1959-09-01 PRIMA…     3 Original    FLOW     
#>  6 5302010  Data1    TABLE 10. … 1959-09-01 PRIMA…     2 Original    FLOW     
#>  7 5302010  Data1    TABLE 10. … 1959-09-01 PRIMA…     0 Original    FLOW     
#>  8 5302010  Data1    TABLE 10. … 1959-09-01 PRIMA…     0 Original    FLOW     
#>  9 5302010  Data1    TABLE 10. … 1959-09-01 PRIMA…    NA Original    FLOW     
#> 10 5302010  Data1    TABLE 10. … 1959-09-01 PRIMA…     1 Original    FLOW     
#> # … with 20,242 more rows, and 4 more variables: collection_month <chr>,
#> #   frequency <chr>, series_id <chr>, unit <chr>
```

<sup>Created on 2020-09-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mitchfscott** [comment]
Thanks a lot for your help Matt - really appreciate it
