### ISSUE TITLE
regex for download_abs_data_cube incompatible with some releases

### ISSUE THREAD

**Issue by hamgamb** [MattCowgill/readabs#81]
Count of Australian Businesses download URL is formatted differently to other releases - specifying beginning and end dates:
`https://www.abs.gov.au/AUSSTATS/abs@.nsf/DetailsPage/8165.0June%202015%20to%20June%202019?OpenDocument`

The current method in download_abs_data_cube returns only `June%202019`

```date <- releases_table %>%
      dplyr::filter(grepl("(Latest)", .data$release)) %>%
      dplyr::pull(.data$release) %>%
      stringr::str_remove(" \\(Latest\\)") %>%
      stringr::str_extract("Week ending \\d+\\s{1}\\w+ \\d+$|(Jan(?:uary)?|Feb(?:ruary)?|Mar(?:ch)?|Apr(?:il)?|May|Jun(?:e)?|Jul(?:y)?|Aug(?:ust)?|Sep(?:tember)?|Oct(?:ober)?|Nov(?:ember)?|Dec(?:ember)?) \\d+$|\\d+$") %>%
      stringr::str_replace_all(" ", "%20")
```

Replacing the str_extract line with:

```
stringr::str_extract("Week ending \\d+\\s{1}\\w+ \\d+$|(Jan(?:uary)?|Feb(?:ruary)?|Mar(?:ch)?|Apr(?:il)?|May|Jun(?:e)?|Jul(?:y)?|Aug(?:ust)?|Sep(?:tember)?|Oct(?:ober)?|Nov(?:ember)?|Dec(?:ember)?).*")
```  

still works with other datacubes (EQ09 as in the example, and the weekly payroll jobs) but also works with the Business Count datacubes.

**Comment by MattCowgill** [comment]
Thanks very much @hamgamb for identifying the issue and the solution! 

Would you consider submitting a pull request?

**Comment by hamgamb** [comment]
@MattCowgill sure. Have not done one before so let me know if I did anything wrong!

**Comment by MattCowgill** [comment]
All good, thanks @hamgamb
