### ISSUE TITLE
Fix download_abs_data_cube for the new website

### ISSUE THREAD

**Issue by daviddiviny** [MattCowgill/readabs#84]
The urls for the new website are in the format: https://beta.abs.gov.au/statistics/labour/employment-and-unemployment/labour-force-australia-detailed/jul-2020/EQ09.xlsx 

This might make it tricky as there is no catalogue number in the url. 

What do you think about asking people to specify "labour-force-australia-detailed" as a string? I think a better solution is to try and refactor to use the API? 

Thoughts @MattCowgill  @HughParsonage @hamgamb ?

**Comment by hamgamb** [comment]
Is there any real difference between knowing that the cat.no is 6291.0.55.001 and knowing that the title is 'labour-force-australia-detailed'?

**Comment by MattCowgill** [comment]
Looks like they've now switched over to the new site.

@daviddiviny, `download_abs_data_cube()` no longer appears to work. The URL in your comment above also doesn't work (it does if you remove the `beta`). 

If it's straightforward to modify the function so that it works with URLs of the new form, that would be great. If not, I guess the function is deprecated for the time being, pending a new approach that works with the API?

**Comment by daviddiviny** [comment]
Yep, I think it is a bit of work to get my head around the new url format, but if anything it should be more robust.

**Comment by daviddiviny** [comment]
So I think this code works on the new site.

Does anyone have  a use case where they don't want to download the most latest data? 

``` r
  latest_url <- "https://www.abs.gov.au/statistics/labour/earnings-and-work-hours/weekly-payroll-jobs-and-wages-australia/latest-release"
  
  latest_page <- read_html(latest_url)
  #Find the url for the download
  download_url <- tibble(url = latest_page %>% html_nodes(".file--x-office-spreadsheet a") %>% html_attr("href")) %>% 
    filter(grepl("DO004", url, ignore.case = TRUE)) %>% 
    pull(url)
  
  #==================download and import data======================
  
  download.file(url = download_url,
                destfile = "raw-data/other-abs/6160055001_do004.xlsx", 
                mode = "wb")


```

**Comment by MattCowgill** [comment]
Great, thanks @daviddiviny.

I'm happy to go with a minimal function that fetches the latest datacube for now. We can always build on that.

**Comment by hamgamb** [comment]
What's the strategy for generating the `latest_url` for different series? ie for the detailed labour force the url is `https://www.abs.gov.au/statistics/labour/employment-and-unemployment/labour-force-australia-detailed-quarterly/`. 
My work around at the moment is using internal data with the theme, parent-topic, and topic hard coded: 
```
|cat_no |theme  |parent_topic                |topic                  |
|:------|:------|:---------------------------|:----------------------|
|6202.0 |labour |employment-and-unemployment |labour-force-australia |
```
which you can generate urls with `glue::glue("https://www.abs.gov.au/statistics/{theme}/{parent_topic}/{topic}/latest-release")` or something similar. 

This doesn't feel like the best way forward, but I don't know of another solution.

**Comment by daviddiviny** [comment]
Can we create a lookup table by scraping this [page](https://github.com/MattCowgill/readabs/issues/84)?

**Comment by hamgamb** [comment]
Yes that should work. 

Something like
```
abs_stats_page <- read_html(abs_stats_url)
base_url <- tibble::tibble(url_prefix = abs_stats_page %>% html_nodes(".layout__region--content") %>% html_nodes("a") %>% html_attr("href")) %>% filter(grepl("/statistics", url))
```

and then append the name of the series with "latest-release"

**Comment by daviddiviny** [comment]
Yep, but I thought we could have an object `abs_lookup_table` that was created like this:

```r 
library(tidyverse)
library(glue)
library(rvest)
library(stringr)

#scrape the main page
abs_stats_page <- read_html("https://www.abs.gov.au/statistics")

main_page_data <- tibble::tibble(heading = abs_stats_page %>% 
                              html_nodes("h3") %>% html_text() %>% str_trim(),
                            url_suffix = abs_stats_page %>% html_nodes(".layout__region--content a") %>% html_attr("href") %>% str_trim()) %>% 
  filter(grepl("/statistics", url_suffix)) %>% 
  filter(heading != "Key economic indicators")

#scrape each page

scrape_sub_page <- function(sub_page_url_suffix){


main_page_heading <- main_page_data$heading[main_page_data$url_suffix == sub_page_url_suffix]


sub_page <- read_html(glue("https://www.abs.gov.au{sub_page_url_suffix}"))

sub_page_data <- tibble::tibble(heading = main_page_heading,
                    sub_heading = sub_page %>% html_nodes(".abs-layout-title") %>% html_text() %>% str_trim(),
                    sub_page_url_suffix = sub_page_url_suffix,
                    catalogue_string = sub_page %>% html_nodes("#content .card") %>% html_attr("href") %>%  
                    str_remove(sub_page_url_suffix) %>% 
                    str_remove("/[^/]*$"))

}


abs_lookup_table <- map_dfr(main_page_data$url_suffix, scrape_sub_page)

usethis::use_data(abs_lookup_table, overwrite = TRUE, internal = TRUE)



```
