### ISSUE TITLE
Issue download tables 11+ cat_no 8501.0

### ISSUE THREAD

**Issue by lauken13** [MattCowgill/readabs#87]
Hi Matt,

Great package! A student ran into some difficulties downloading tables 11+ (1-10 work fine) in cat no 8501.0. I took a look at the code but I don't understand enough about how the indexing works to make a pull request. :)

Error in .f(.x[[i]], ...) : 
  Cannot find valid entry for cat_no  in the ABS Time Series Directory

**Comment by MattCowgill** [comment]
Hi @lauken13. Thanks for raising this. Tables 14, 15 and 16 seem to work OK, but 11-13 don't. It seems to be an issue with the ABS Time Series Directory. I'll raise this with the ABS.

**Comment by lauken13** [comment]
Thanks so much Matt!

**Comment by MattCowgill** [comment]
Hi @lauken13, the ABS has fixed the issue with tables 11-13 now, so your students should be able to fetch those tables: 

``` r
read_abs("8501.0", 11)
#> Error in read_abs("8501.0", 11): could not find function "read_abs"
```

<sup>Created on 2020-09-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by MattCowgill** [comment]
Hi @lauken13, there are some other tables in the 8501.0 release that may have caused problems. The ABS tells me that these problems have been fixed in the data that will be released at 11:30 today.

**Comment by lauken13** [comment]
Excellent, thanks Matt! Thanks for following up! :)
