### ISSUE TITLE
Adding readabs into Conda for supporting readabs in Conda-based virtual env

### ISSUE THREAD

**Issue by efendyk** [MattCowgill/readabs#92]
Hi,

Has anyone tried to add readabs into Conda-based virtual environment using yml requirement file?
I think this will require building the compiled code and published into a Conda channel such as Conda Forge. I tried [this](https://tobiasraabe.github.io/blog/how-to-compile-and-distribute-an-r-package-with-conda.html) but there are dependency issues such as hutils that is not in Conda.

Any thoughts?

Thanks,

**Comment by MattCowgill** [comment]
Hi, 
I'm afraid I have no experience with Conda and am unable to help with this.
