### ISSUE TITLE
`scrape_abs_catalogues()` is broken

### ISSUE THREAD

**Issue by MattCowgill** [MattCowgill/readabs#93]
``` r
readabs:::scrape_abs_catalogues()
#> Error: Tibble columns must have compatible sizes.
#> * Size 38: Existing data.
#> * Size 28: Column `url_suffix`.
#> ℹ Only values of size one are recycled.
```

<sup>Created on 2020-10-31 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by daviddiviny** [comment]
Fixed in a pull request.

**Comment by MattCowgill** [comment]
thanks very much @daviddiviny! I'd planned to look at this this week (this issue was mostly a note to self). Thanks for fixing it. It looks like there are still (unrelated?) errors, so I'll merge into a non-master branch and try to fix the errors

**Comment by MattCowgill** [comment]
seems to be all good now, just needed to refresh the internal data so that tests would pass
