### ISSUE TITLE
Add convenience function(s) to fetch ABS payrolls data

### ISSUE THREAD

**Issue by MattCowgill** [MattCowgill/readabs#99]

**Comment by MattCowgill** [comment]
Will use `download_abs_data_cube()` and some tidying

**Comment by daviddiviny** [comment]
I have the tidying code for this. Some of it relies on `strayr`.

**Comment by MattCowgill** [comment]
Cool @daviddiviny! I'm hesitant to add a `strayr` dependency, as that would require me to submit `strayr` to CRAN which I can't be bothered doing. 

My general approach with readabs is that the user should get the ABS data, as published, with minimal-to-no changes. In this case I'm thinking I'll change "0. Australia" to "Australia", "01. A-Agriculture, forestry & fishing" to "Agriculture, forestry & fishing" etc. but otherwise pretty much leave it intact. What do you think?

I'm halfway done on a function for this, would value your view on a commit

**Comment by daviddiviny** [comment]
Ok sure thing. 

Here is some code that might help. It throws a few warnings that you might want to try and clear up for the package. 

```r
table_4_wages_clean <- table_4_wages_raw %>% 
  rename_at(vars(starts_with("4")), .funs = convert_excel_date) %>% 
  clean_names() %>% 
  filter(!is.na(state_or_territory)) %>% 
  pivot_longer(cols = starts_with("week_ending"), names_prefix = "week_ending_", names_to = "week_ending") %>% 
  mutate(series = "wages",
         week_ending = as.Date(str_replace_all(week_ending,pattern = "_", "-")),
         value = as.numeric(value)) %>% 
  mutate_at(vars(state_or_territory:age_group), funs(str_remove(., pattern = "\\d+\\. "))) %>% 
  mutate(industry_division = str_remove(industry_division,  "[:upper:]?-+"),
         industry_division = tools::toTitleCase(industry_division),
         industry_division = str_replace_all(industry_division, "&", "and"),
         sex = str_remove_all(sex, "s$"))
         
```

**Comment by daviddiviny** [comment]
```r

#function to convert excel numeric string to date
convert_excel_date <- function(x){
  x <- as.Date(as.numeric(x), origin = "1899-12-30")
  x <- glue("week_ending_{x}")
  return(x)
}

```

**Comment by MattCowgill** [comment]
please let me know if you have any comments on the `read_payrolls()` function in this PR @daviddiviny https://github.com/MattCowgill/readabs/pull/100
